//! 更新默认主题配置后，需要执行 npm run build:theme 重新构建index.json

const fs = require('fs')
const path = require('path')
const { createThemeColors } = require('./utils')

const defaultThemes = [
  {
    id: 'green',
    name: '绿意盎然',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(77, 175, 124)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#4baed5',
      '--color-badge-tertiary': '#e7aa36',
    },
  },
  {
    id: 'blue',
    name: '蓝田生玉',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(52, 152, 219)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#5cbf9b',
      '--color-badge-tertiary': '#5cbf9b',
    },
  },
  {
    id: 'blue_plus',
    name: '蛋雅深蓝',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(77, 131, 175)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-600)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': 'rgba(66.6, 150.7, 171, 1)',
      '--color-badge-tertiary': 'rgba(54, 196, 231, 1)',
    },
  },
  {
    id: 'orange',
    name: '橙黄橘绿',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(245, 171, 53)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#9ed458',
      '--color-badge-tertiary': '#9ed458',
    },
  },
  {
    id: 'red',
    name: '热情似火',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(214, 69, 65)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#dfbb6b',
      '--color-badge-tertiary': '#dfbb6b',
    },
  },
  {
    id: 'pink',
    name: '粉装玉琢',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(241, 130, 141)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#f5b684',
      '--color-badge-tertiary': '#f5b684',
    },
  },
  {
    id: 'purple',
    name: '重斤球紫',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(155, 89, 182)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#e5a39f',
      '--color-badge-tertiary': '#e5a39f',
    },
  },
  {
    id: 'grey',
    name: '灰常美丽',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(108, 122, 137)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#b19b9f',
      '--color-badge-tertiary': '#b19b9f',
    },
  },
  {
    id: 'ming',
    name: '青出于黑',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(51, 110, 123)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#6376a2',
      '--color-badge-tertiary': '#6376a2',
    },
  },
  {
    id: 'blue2',
    name: '清热板蓝',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(79, 98, 208)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'var(--color-primary-light-600-alpha-700)',
      '--color-main-background': 'rgba(255, 255, 255, 1)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#b080db',
      '--color-badge-tertiary': '#b080db',
    },
  },
  {
    id: 'black',
    name: '黑灯瞎火',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(150, 150, 150)',
      font: 'rgb(229, 229, 229)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(19, 19, 19, 0.9)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'url(./theme_images/landingMoon.png)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary-dark-200)',
      '--color-badge-secondary': 'var(--color-primary)',
      '--color-badge-tertiary': 'var(--color-primary-dark-300)',
    },
  },
  {
    id: 'mid_autumn',
    name: '月里嫦娥',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(74, 55, 82)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'rgba(255, 255, 255, 0)',
      '--color-main-background': 'rgba(255, 255, 255, 0.9)',
      '--color-nav-font': 'var(--color-primary-light-600)',
      '--background-image': 'url(./theme_images/jqbg.jpg)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',


      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': '#af9479',
      '--color-badge-tertiary': '#af9479',
    },
  },
  {
    id: 'naruto',
    name: '木叶之村',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(87, 144, 167)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'rgba(255, 255, 255, 0.15)',
      '--color-main-background': 'rgba(255, 255, 255, 0.8)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'url(./theme_images/myzcbg.jpg)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': 'var(--color-primary)',
      '--color-badge-secondary': 'var(--color-primary-light-100)',
      '--color-badge-tertiary': 'var(--color-primary-light-100)',
    },
  },
  {
    id: 'china_ink',
    name: '近墨者黑',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgba(47, 47, 47, 1)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'rgba(255, 255, 255, 0)',
      '--color-main-background': 'rgba(255, 255, 255, 0.8)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'url(./theme_images/china_ink.jpg)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',


      '--color-btn-hide': 'rgba(183, 212, 208, 1)',
      '--color-btn-min': 'rgba(200, 214, 183, 1)',
      '--color-btn-close': 'rgba(218, 195, 188, 1)',

      '--color-badge-primary': 'rgba(137, 70, 70, 1)',
      '--color-badge-secondary': 'rgba(67, 139, 65, 1)',
      '--color-badge-tertiary': 'rgba(132, 135, 65, 1)',
    },
  },
  {
    id: 'happy_new_year',
    name: '新年快乐',
    isDark: false,
    isDarkFont: false,
    config: {
      primary: 'rgb(192, 57, 43)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': 'rgba(255, 255, 255, 0.15)',
      '--color-main-background': 'rgba(255, 255, 255, 0.8)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'url(./theme_images/xnkl.png)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',

      '--color-btn-hide': '#3bc2b2',
      '--color-btn-min': '#85c43b',
      '--color-btn-close': '#fab4a0',

      '--color-badge-primary': '#7fb575',
      '--color-badge-secondary': '#dfbb6b',
      '--color-badge-tertiary': 'var(--color-primary-light-100)',
    },
  },
  // === Glass Themes ===
  {
    id: 'glass_cosmos',
    name: '深空蓝',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(0, 170, 255)',
      font: 'rgb(230, 245, 255)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(10, 20, 50, 0.12)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'radial-gradient(ellipse at 42% 38%, rgba(18,45,90,0.95) 0%, rgba(6,13,31,0.7) 40%, rgba(2,5,15,1) 100%)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--glass-blur': '20px',
      '--glass-border-glow': '1px solid rgba(255,255,255,0.08)',
      '--glass-accent-line': 'rgba(0,140,255,0.5)',
      '--glass-self-glow': 'rgba(0,100,220,0.03)',
      '--color-btn-hide': 'rgba(0,140,220,0.6)',
      '--color-btn-min': 'rgba(0,100,180,0.5)',
      '--color-btn-close': 'rgba(0,80,160,0.4)',
      '--color-badge-primary': 'rgb(0, 170, 255)',
      '--color-badge-secondary': 'rgb(64, 196, 255)',
      '--color-badge-tertiary': 'rgb(128, 213, 255)',
    },
  },
  {
    id: 'glass_amber',
    name: '琥珀暖光',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(255, 170, 50)',
      font: 'rgb(255, 240, 220)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(20, 12, 4, 0.12)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'radial-gradient(ellipse at 42% 38%, rgba(55,32,8,0.95) 0%, rgba(13,8,2,0.7) 40%, rgba(3,2,1,1) 100%)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--glass-blur': '20px',
      '--glass-border-glow': '1px solid rgba(255,255,255,0.08)',
      '--glass-accent-line': 'rgba(255,150,30,0.5)',
      '--glass-self-glow': 'rgba(200,120,10,0.03)',
      '--color-btn-hide': 'rgba(220,130,10,0.6)',
      '--color-btn-min': 'rgba(180,100,8,0.5)',
      '--color-btn-close': 'rgba(140,70,5,0.4)',
      '--color-badge-primary': 'rgb(255, 170, 50)',
      '--color-badge-secondary': 'rgb(255, 200, 100)',
      '--color-badge-tertiary': 'rgb(255, 220, 150)',
    },
  },
  {
    id: 'glass_emerald',
    name: '翡翠幽光',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(0, 200, 140)',
      font: 'rgb(220, 255, 240)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(4, 20, 12, 0.12)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'radial-gradient(ellipse at 42% 38%, rgba(10,50,32,0.95) 0%, rgba(2,13,8,0.7) 40%, rgba(1,3,2,1) 100%)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--glass-blur': '20px',
      '--glass-border-glow': '1px solid rgba(255,255,255,0.08)',
      '--glass-accent-line': 'rgba(0,190,150,0.5)',
      '--glass-self-glow': 'rgba(0,140,110,0.03)',
      '--color-btn-hide': 'rgba(0,160,110,0.6)',
      '--color-btn-min': 'rgba(0,120,80,0.5)',
      '--color-btn-close': 'rgba(0,90,60,0.4)',
      '--color-badge-primary': 'rgb(0, 200, 140)',
      '--color-badge-secondary': 'rgb(80, 220, 170)',
      '--color-badge-tertiary': 'rgb(140, 235, 200)',
    },
  },
  {
    id: 'glass_crimson',
    name: '绯红暗焰',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(255, 60, 60)',
      font: 'rgb(255, 230, 230)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(24, 4, 8, 0.12)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'radial-gradient(ellipse at 42% 38%, rgba(55,10,16,0.95) 0%, rgba(13,2,4,0.7) 40%, rgba(3,1,1,1) 100%)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--glass-blur': '20px',
      '--glass-border-glow': '1px solid rgba(255,255,255,0.08)',
      '--glass-accent-line': 'rgba(255,55,55,0.5)',
      '--glass-self-glow': 'rgba(180,30,30,0.03)',
      '--color-btn-hide': 'rgba(220,40,40,0.6)',
      '--color-btn-min': 'rgba(180,30,30,0.5)',
      '--color-btn-close': 'rgba(140,20,20,0.4)',
      '--color-badge-primary': 'rgb(255, 60, 60)',
      '--color-badge-secondary': 'rgb(255, 110, 110)',
      '--color-badge-tertiary': 'rgb(255, 160, 160)',
    },
  },
  {
    id: 'glass_violet',
    name: '紫晶幻境',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(160, 80, 240)',
      font: 'rgb(240, 220, 255)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(18, 4, 30, 0.12)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'radial-gradient(ellipse at 42% 38%, rgba(38,12,55,0.95) 0%, rgba(8,2,16,0.7) 40%, rgba(2,1,4,1) 100%)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--glass-blur': '20px',
      '--glass-border-glow': '1px solid rgba(255,255,255,0.08)',
      '--glass-accent-line': 'rgba(150,65,240,0.5)',
      '--glass-self-glow': 'rgba(120,40,180,0.03)',
      '--color-btn-hide': 'rgba(140,50,200,0.6)',
      '--color-btn-min': 'rgba(110,35,160,0.5)',
      '--color-btn-close': 'rgba(80,20,120,0.4)',
      '--color-badge-primary': 'rgb(160, 80, 240)',
      '--color-badge-secondary': 'rgb(190, 130, 255)',
      '--color-badge-tertiary': 'rgb(210, 170, 255)',
    },
  },
  {
    id: 'glass_arctic',
    name: '极地冰蓝',
    isDark: true,
    isDarkFont: false,
    config: {
      primary: 'rgb(0, 210, 190)',
      font: 'rgb(220, 250, 255)',
      '--color-app-background': 'rgba(0, 0, 0, 0)',
      '--color-main-background': 'rgba(4, 18, 26, 0.12)',
      '--color-nav-font': 'var(--color-primary)',
      '--background-image': 'radial-gradient(ellipse at 42% 38%, rgba(10,45,55,0.95) 0%, rgba(2,13,18,0.7) 40%, rgba(1,3,5,1) 100%)',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--glass-blur': '20px',
      '--glass-border-glow': '1px solid rgba(255,255,255,0.08)',
      '--glass-accent-line': 'rgba(0,200,190,0.5)',
      '--glass-self-glow': 'rgba(0,150,140,0.03)',
      '--color-btn-hide': 'rgba(0,170,160,0.6)',
      '--color-btn-min': 'rgba(0,130,120,0.5)',
      '--color-btn-close': 'rgba(0,100,90,0.4)',
      '--color-badge-primary': 'rgb(0, 210, 190)',
      '--color-badge-secondary': 'rgb(80, 230, 210)',
      '--color-badge-tertiary': 'rgb(150, 240, 230)',
    },
  },
]

const themes = defaultThemes.map(({ config: { primary, font, ...extInfo }, ...themeInfo }) => {
  return {
    ...themeInfo,
    isCustom: false,
    config: {
      themeColors: createThemeColors(primary, font, themeInfo.isDark),
      extInfo,
    },
  }
})

fs.writeFileSync(path.join(__dirname, 'index.json'), JSON.stringify(themes, null, 2))

